server:
  port: 8080

spring:
   application:
   name: crud-operation

   datasource:
     url: jdbc:mysql://localhost:9095/hall_booking
     username: root
     password: nassir@123

   jpa:
     show-sql: true
     hibernate:
       ddl-auto: update
     properties:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true

#server:
#  port: 2002
#
#spring:
#  application:
#    name: crud-operation
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/hall_booking
#    username: root
#    password: nassir@123
#
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#        transaction:
#          jta:
#            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
#

# server:
#   port: 8080

# spring:
#   application:
#     name: crud-operation

#   datasource:
#     url: jdbc:mysql://localhost:9095/hall_booking
#     username: root
#     password: nassir@123

#   jpa:
#     show-sql: true
#     hibernate:
#       ddl-auto: update
#     properties:
#       hibernate:
#         dialect: org.hibernate.dialect.MySQLDialect
#         format_sql: true
#jhnj




